baseURL = "https://archive.typhoon.network/"
languageCode = "en-us"
title = "Typhoon Network Archive"
theme = "ananke"

DefaultContentLanguage = "en"
paginate = 12

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Typhoon Network"
  github = "https://github.com/typhoonnetwork"
  og_image = "/img/socialbanner.png"
  sitename = "Typhoon Network"
  twitter = "@networktyphoon"
